apiVersion: v1
kind: Pod
metadata:
  name: mypod
  namespace: myservice
  labels:
    dc: us-west-1
    group: gamma
spec:
  os: linux
  containers:
    - name: my_container_name
      image: registry.bigbrother.io/myimage:v1.2.0
      ports:
        - containerPort: 8080
          protocol: TCP
      readinessProbe:
        httpGet:
          path: /ready
          port: 8080
      livenessProbe:
        httpGet:
          path: /alive
          port: 8080
      resources:
        limits:
          cpu: 2
          memory: "500Mi"
        requests:
          cpu: 1
          memory: "500Mi"